version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "This is the build job"
  clone:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - attach_workspace:
          at: ~/my-app-backend
      - add_ssh_keys:
          fingerprints:
            - "SHA256:tQuG3CavqctmCPxlH+PgzZ4U6s+OGU6HcTODN6nHDV4"
      - run:
          name: Clone frontend repository
          command: >-
            GIT_SSH_COMMAND='ssh -i ~/.ssh/id_rsa_fingerprint'
            git clone git@github.com:avinash-yamani-devops/circleci-test.git ~/my-app-frontend

      - run: echo "This is the test job"
  

workflows:
  build_workflow:
    jobs:
      - build
      - clone
